from typing import Generic, List, TypeVar
from pydantic import BaseModel

from models.keywords import ActorId, ItemId, LocationId
from models.observables import ObservableAction, ObservableActorState, ObservableEvent, ObservableItemState, ObservableLocationState, ObservableOutcome, ObservableState


class Generation(BaseModel):
    pass

KEY_TYPE = TypeVar("KEY_TYPE")
VALUE_TYPE = TypeVar("VALUE_TYPE")
class GeneratableTuple(Generation, Generic[KEY_TYPE,VALUE_TYPE]):
    key: KEY_TYPE
    value: VALUE_TYPE

class ActorStateTuple(GeneratableTuple[ActorId,ObservableActorState]):
    pass

class LocationStateTuple(GeneratableTuple[LocationId,ObservableLocationState]):
    pass

class ItemStateTuple(GeneratableTuple[ItemId,ObservableItemState]):
    pass

class ActorAgentGeneration(Generation):
    """
    The output generated by an actor agent. 
    Actors observe facts about their environment, situation, and character, the generate facts about their character's responses and actions,
    as well as specify any resultant changes in the observable state to actors, locations, or items.
    """

    """Facts representing the outcomes of actions targeting this character. There should be at most one outcome for each action."""
    resulting_outcomes: List[ObservableOutcome]

    """Facts representing the responses and actions taken by the character. This should be limited to a reasonable amount of activity
    can be accomplished in a 10 second span."""
    resulting_actions: List[ObservableAction]

    """Facts representing any triggered events that may occur due to interaction with an item or location."""
    resulting_events: List[ObservableEvent]

    """Any changes in characters' observable state resulting from resulting_outcomes, resulting_actions, or resulting_events"""
    new_actor_states: List[ActorStateTuple]

    """Any changes in items' observable state resulting from resulting_outcomes, resulting_actions, or resulting_events"""
    new_item_states: List[ItemStateTuple]

    """Any changes in locations' observable state resulting from resulting_outcomes, resulting_actions, or resulting_events"""
    new_location_states: List[LocationStateTuple]